### ISSUE TITLE
Builds not... building

### ISSUE THREAD

**Issue by Rjvs** [StirlingLabs/Version.Net#2]
e.g. in StirlingLabs.Logging which is now using Version.Net as a submodule, `dotnet build StirlingLogging -c Release` completes with no errors but doesn’t actually build anything…

**Comment by TYoungSL** [comment]
3 problems;

> ```/home/runner/work/Logging/Logging/StirlingLabs.Version/Version.proj(101,13): error MSB4186: Invalid static method invocation syntax: "[MsBuild]::Add($(GitBaseVersionPatch),1)". Method '[MSBuild]::Add' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order. [/home/runner/work/Logging/Logging/StirlingLogging/StirlingLogging.csproj]```

This was caused by the binder not being able to resolve `MsBuild.Add(<nullable>,int)` as `GitBaseVersionPatch` was missing. The check to see if it the `GitBaseTag` was unset was absent. (Fix 1)

`GitBaseVersionPatch` was unset because the tags were not fetched in the context of the shallow repo. Added a prereq to check for shallow repo and fetch tags. (Fix 2)

The resolution of the latest version by tag using git was done by sorting by `-v:refname` which gave the wrong tag. This is because `v21.6` is greater than `v21.07` when comparing strings. Switched to ordering by `-committerdate` instead. (Fix 3)
